# Generated by Django 5.2.8 on 2025-11-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_populate_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
    ]
